"""
build_nonperfect_match_review.py — Regenerate the non-perfect-match review.

Reads:
  harmonization_outputs/validation_summary.csv
  harmonization_outputs/validation_report.csv

Writes:
  harmonization_outputs/nonperfect_match_review.md

Scope: every (trial, column) cell with match_rate < 1.0 in the 9-trial template,
excluding three policy-driven unresolved fields:
  - bor_bin (all trials)
  - pfs_bin (all trials)
  - CIMAC-s1400i age

The report classifies each cell into one of three severity groups based on
deterministic rules (no manual judgment baked into output):

  A — minor / rounding: numeric-only mismatches with abs difference <=1 day
  C — wider unresolved: >=50 missing_in_reproduced rows for the same field
  B — systematic-bounded: everything else
"""
from __future__ import annotations

import argparse
import logging
from pathlib import Path

import numpy as np
import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUTDIR = PROJECT_ROOT / "harmonization_outputs"

LOG = logging.getLogger("nonperfect-review")

POLICY_EXCLUDE_FIELDS = {"bor_bin", "pfs_bin"}
POLICY_EXCLUDE_CELLS  = {("CIMAC-s1400i", "age")}


def classify_group(mismatch_rows: pd.DataFrame) -> str:
    """Heuristic group A / B / C based on mismatch composition."""
    if mismatch_rows.empty:
        return "A"

    kinds = mismatch_rows["mismatch_kind"].value_counts().to_dict()
    n = len(mismatch_rows)

    # A: numeric-only with abs diff ≤ 1
    if set(kinds.keys()) <= {"numeric_diff"}:
        try:
            t = pd.to_numeric(mismatch_rows["template_value"], errors="coerce")
            r = pd.to_numeric(mismatch_rows["reproduced_value"], errors="coerce")
            diff = (t - r).dropna()
            if len(diff) and diff.abs().max() <= 1:
                return "A"
        except Exception:
            pass

    # C: many missing_in_reproduced (>=50 rows)
    if kinds.get("missing_in_reproduced", 0) >= 50:
        return "C"

    return "B"


def diff_summary(mismatch_rows: pd.DataFrame) -> str:
    """Compact human-readable summary of the mismatch pattern."""
    if mismatch_rows.empty:
        return "(no mismatches)"
    kinds = mismatch_rows["mismatch_kind"].value_counts().to_dict()
    parts = [f"{v} {k}" for k, v in kinds.items()]
    # numeric stats if any
    try:
        t = pd.to_numeric(mismatch_rows["template_value"], errors="coerce")
        r = pd.to_numeric(mismatch_rows["reproduced_value"], errors="coerce")
        diff = (t - r).dropna()
        if len(diff):
            parts.append(
                f"numeric diff: median={diff.median():.1f}, abs_max={diff.abs().max():.1f}"
            )
    except Exception:
        pass
    return "; ".join(parts)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(OUTDIR / "nonperfect_match_review.md"))
    ap.add_argument("--summary", default=str(OUTDIR / "validation_summary.csv"))
    ap.add_argument("--report",  default=str(OUTDIR / "validation_report.csv"))
    args = ap.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")

    vs = pd.read_csv(args.summary)
    vr = pd.read_csv(args.report)

    nonperfect = vs[(vs["match_rate"] < 1.0) & (~vs["column"].isin(POLICY_EXCLUDE_FIELDS))].copy()
    nonperfect = nonperfect[~nonperfect.apply(
        lambda r: (r["trial"], r["column"]) in POLICY_EXCLUDE_CELLS, axis=1
    )]
    nonperfect = nonperfect.sort_values(["match_rate", "trial", "column"]).reset_index(drop=True)

    # Attach group + summary text per row
    rows = []
    for _, r in nonperfect.iterrows():
        sub = vr[(vr["trial"] == r["trial"]) & (vr["column"] == r["column"])]
        rows.append({
            "trial": r["trial"],
            "column": r["column"],
            "match_rate": float(r["match_rate"]),
            "n_rows": int(r["n_rows"]),
            "n_mismatch": int(r["n_rows"] - r["n_match"]),
            "group": classify_group(sub),
            "pattern": diff_summary(sub),
        })
    detail = pd.DataFrame(rows)

    # Aggregate counts
    group_counts = detail["group"].value_counts().to_dict()
    group_rows = detail.groupby("group")["n_mismatch"].sum().to_dict()

    # ─── Build markdown ────────────────────────────────────────────────
    lines: list[str] = []
    lines.append("# Non-perfect match review")
    lines.append("")
    lines.append("Generated by `scripts/build_nonperfect_match_review.py` from "
                 "`validation_summary.csv` and `validation_report.csv`. "
                 "No code or harmonized outputs changed in producing this report.")
    lines.append("")
    lines.append("Scope: every (trial, column) cell with `match_rate < 1.0` in the 9-trial template, ")
    lines.append("**excluding** the three policy-driven unresolved fields:")
    lines.append("")
    lines.append("- `bor_bin` (all trials — hypothesis 78–86%, not committed)")
    lines.append("- `pfs_bin` (all trials — hypothesis ~81%, not committed)")
    lines.append("- `CIMAC-s1400i` `age` (per-sample decimal age; no collection-date source)")
    lines.append("")
    lines.append(f"{len(detail)} non-perfect cells remain. Severity classification:")
    lines.append("")
    lines.append("| Group | Description | Cells | Rows affected |")
    lines.append("|---|---|---:|---:|")
    desc = {
        "A": "Minor / rounding — numeric-only, abs diff ≤ 1 day",
        "B": "Systematic-bounded — known pattern affecting a subset",
        "C": "Wider unresolved — ≥50 missing-in-reproduced rows",
    }
    for g in ("A", "B", "C"):
        lines.append(f"| {g} | {desc[g]} | {group_counts.get(g, 0)} | {group_rows.get(g, 0)} |")
    lines.append("")

    # Detail tables per group
    for g in ("C", "B", "A"):
        sub = detail[detail["group"] == g].copy()
        if sub.empty:
            continue
        lines.append(f"## Group {g} — {desc[g]} ({len(sub)} cells)")
        lines.append("")
        lines.append("| trial | field | match | n_mismatch | pattern |")
        lines.append("|---|---|---:|---:|---|")
        for _, r in sub.sort_values("match_rate").iterrows():
            lines.append(
                f"| {r['trial']} | `{r['column']}` | {r['match_rate']:.3f} | "
                f"{r['n_mismatch']} | {r['pattern']} |"
            )
        lines.append("")

    # GU16-257 pfs_time note — only if still non-perfect (post-fallback this is 0.98)
    gu_pfs = detail[(detail["trial"] == "CIMAC-gu16257") & (detail["column"] == "pfs_time")]
    if not gu_pfs.empty:
        r = gu_pfs.iloc[0]
        lines.append("### Note: CIMAC-gu16257 `pfs_time`")
        lines.append("")
        lines.append(f"Current match rate {r['match_rate']:.3f} ({r['n_mismatch']} mismatches). ")
        lines.append("See `gu16257_pfs_time_fallback_investigation.md` for the column-level analysis ")
        lines.append("that motivated the current `DFSTIM ?? DRFSTIM` fallback rule.")
        lines.append("")

    # Block-use summary
    lines.append("## Block-use assessment")
    lines.append("")
    group_c = detail[detail["group"] == "C"]
    if group_c.empty:
        lines.append("**No cell warrants blocking** use of `harmonized_11trials.csv` at the table level. "
                     "Group A cells are semantically equivalent (rounding). Group B cells have well-understood "
                     "patterns affecting bounded subsets — none corrupt the underlying value.")
    else:
        lines.append(f"**{len(group_c)} cell(s) warrant caution**:")
        for _, r in group_c.iterrows():
            lines.append(f"- `{r['trial']}` `{r['column']}` (match {r['match_rate']:.3f}, {r['n_mismatch']} mismatches)")
    lines.append("")

    # Reviewer next steps (deterministic from the data)
    lines.append("## Recommended next-action order (highest leverage first)")
    lines.append("")
    for i, (_, r) in enumerate(detail.sort_values(["match_rate"]).iterrows(), 1):
        lines.append(f"{i}. **{r['trial']}** `{r['column']}` — match {r['match_rate']:.3f}, "
                     f"{r['n_mismatch']} rows; pattern: {r['pattern']}")
    lines.append("")

    Path(args.out).write_text("\n".join(lines))
    LOG.info("Wrote %s (%d non-perfect cells)", args.out, len(detail))


if __name__ == "__main__":
    main()
