"""
build_final_handoff.py — Final handoff report for human review.

Reads the current harmonization_outputs/ state and produces:
  - harmonization_outputs/final_handoff_report.md
  - harmonization_outputs/final_handoff_report.csv

The CSV is a flat (trial, field, status, n_rows, match_rate, action) table the
reviewer can sort/filter.  The MD is a narrative + per-trial breakdown.
"""
from __future__ import annotations

import argparse
import logging
from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUTDIR       = PROJECT_ROOT / "harmonization_outputs"

LOG = logging.getLogger("handoff")

TEMPLATE_TRIALS = {
    "CIMAC-9204", "CIMAC-10021", "10026", "10104", "ABTC1603",
    "CIMAC-e4412", "EAY131_Z1D", "CIMAC-gu16257", "CIMAC-s1400i",
}


def build_csv_table(harmonized: pd.DataFrame, val_sum: pd.DataFrame, flagged: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for trial in sorted(set(harmonized["trial"].dropna().unique())):
        sub = harmonized[harmonized["trial"] == trial]
        n_rows_trial = len(sub)
        is_template = trial in TEMPLATE_TRIALS
        for field in sub.columns:
            if field in ("cimac_part_id", "trial"):
                continue
            n_na = int(sub[field].isna().sum())
            n_pop = n_rows_trial - n_na
            vs = val_sum[(val_sum["trial"] == trial) & (val_sum["column"] == field)]
            match_rate = float(vs["match_rate"].iloc[0]) if not vs.empty else None
            n_flag = int(((flagged["trial"] == trial) & (flagged["harmonized_field"] == field)).sum())
            status = classify_status(is_template, match_rate, n_pop, n_rows_trial, n_flag)
            rows.append({
                "trial": trial,
                "field": field,
                "is_template_trial": is_template,
                "n_rows": n_rows_trial,
                "n_populated": n_pop,
                "n_NA": n_na,
                "n_flagged": n_flag,
                "match_rate_vs_template": match_rate,
                "status": status,
            })
    df = pd.DataFrame(rows)
    return df.sort_values(["trial", "field"])


def classify_status(is_template: bool, match_rate: float | None, n_pop: int, n_rows: int, n_flag: int) -> str:
    if is_template and match_rate is not None:
        if match_rate >= 0.95:
            return "OK"
        if match_rate >= 0.80:
            return "MOSTLY_OK"
        if match_rate >= 0.40:
            return "PARTIAL"
        return "NEEDS_REVIEW"
    # new-trial fields
    if n_pop == 0:
        return "ALL_NA"
    if n_flag >= n_rows * 0.50:
        return "MOSTLY_FLAGGED"
    return "POPULATED_FROM_SOURCE"


def write_md(handoff_csv: pd.DataFrame, val_sum: pd.DataFrame, harmonized: pd.DataFrame, flagged: pd.DataFrame, prov: pd.DataFrame, md_path: Path, row_order: pd.DataFrame | None = None) -> None:
    lines: list[str] = []
    lines.append("# Final handoff report — CIMAC clinical harmonization")
    lines.append("")
    lines.append("Generated by `scripts/build_final_handoff.py` from the current "
                 "state of `harmonization_outputs/`.")
    lines.append("")

    # ── Section 1: deliverable files ────────────────────────────────────
    lines.append("## 1. Final output files")
    lines.append("")
    files = [
        ("harmonized_9trials_reproduced.csv", "Reproduction of the original 9-trial template (1781 rows, aligned to template row order)"),
        ("harmonized_11trials.csv",          f"Final 11-trial harmonized table ({len(harmonized)} rows: 9 template + 2 new)"),
        ("provenance_long.csv",              f"{len(prov):,} cells with full trail (trial, cimac_part_id, Cimac.id, Collection_Event, harmonized_field, value, confidence, source_file, source_column, source_row_idx, extraction_method, notes)"),
        ("flagged_for_review.csv",           f"{len(flagged)} below-threshold cells with proposed mapping, reason, and reviewer question"),
        ("validation_report.csv",            "Cell-level template vs reproduced mismatches"),
        ("validation_summary.csv",           "Per-(trial, column) match rate"),
        ("row_order_diagnostics.csv",        "9-trial template alignment audit (missing/extra/duplicate keys)"),
        ("source_evidence_report.csv",       "Per (trial, harmonized_field): source files/columns, methods, confidence"),
        ("template_anomalies.csv",           "Known data-quality bugs in the original template, preserved verbatim"),
        ("human_review_summary.txt",         "Text summary of pipeline run + tested hypotheses"),
        ("review_priority_checklist.csv",    "Prioritized open items (P1/P2/P3)"),
        ("review_priority_checklist.md",     "Same checklist, readable form"),
        ("final_handoff_report.md",          "This file"),
        ("final_handoff_report.csv",         "Per-(trial, field) status with match_rate, n_NA, n_flagged"),
        ("file_inventory.csv",               "Inventory of every source file across the 11 trial dirs"),
        ("duplicate_files.csv",              "Source files with identical sha256 content"),
        ("headers_by_file.json",             "Per-file column headers + sheet info"),
        ("inspect_summary.txt",              "Per-trial source-file summary"),
        ("exclusion_and_order_checks.txt",   "Quick post-run checks: BACCI exclusion + 9-trial row order"),
    ]
    # Two files are special-cased so a clean wrapper run never reports
    # them as "(missing)":
    #  * final_handoff_report.md — this file, being written right now;
    #  * exclusion_and_order_checks.txt — produced AFTER this step by the
    #    last wrapper stage (build_exclusion_and_order_checks.py).
    deferred = {
        "final_handoff_report.md":          "this file",
        "exclusion_and_order_checks.txt":   "written by final pipeline step",
    }
    for fname, desc in files:
        if fname in deferred:
            size_str = deferred[fname]
        else:
            path = OUTDIR / fname
            size_str = f"{path.stat().st_size:,} bytes" if path.exists() else "(missing)"
        lines.append(f"- **{fname}** ({size_str}) — {desc}")
    lines.append("")

    # ── Section 2: final validation summary ─────────────────────────────
    lines.append("## 2. Final validation summary (9 template trials)")
    lines.append("")
    pivot = val_sum.pivot(index="column", columns="trial", values="match_rate").round(3)
    lines.append("```")
    lines.append(pivot.fillna("-").to_string())
    lines.append("```")
    lines.append("")
    # OK / mostly_ok / partial / needs_review counts (template trials only)
    tpl_only = handoff_csv[handoff_csv["is_template_trial"]]
    status_counts = tpl_only["status"].value_counts().to_dict()
    lines.append("Status counts across **9 template trials × 15 measurable columns = 135 (trial, column) cells**:")
    for s in ("OK", "MOSTLY_OK", "PARTIAL", "NEEDS_REVIEW"):
        lines.append(f"- {s}: {status_counts.get(s, 0)}")
    lines.append("")

    # Row-order audit for the 9-trial reproduction.
    if row_order is not None and not row_order.empty:
        summary_row = row_order[row_order["issue_type"] == "summary"]
        issues = row_order[row_order["issue_type"] != "summary"]
        lines.append("### Row-order audit (9-trial reproduction vs template)")
        lines.append("")
        if not summary_row.empty:
            lines.append(f"- {summary_row.iloc[0]['note']}")
        lines.append(f"- Diagnostic rows beyond summary: **{len(issues)}** "
                     "(0 means a perfect 1:1 alignment).")
        if not issues.empty:
            counts = issues["issue_type"].value_counts().to_dict()
            for k, v in counts.items():
                lines.append(f"  - `{k}`: {v}")
        lines.append("")
        lines.append("Full detail in `row_order_diagnostics.csv`.")
        lines.append("")

    # ── Section 3: intentionally unresolved ──────────────────────────────
    lines.append("## 3. Fields still intentionally unresolved")
    lines.append("")
    lines.append("These remain `NA` in the harmonized output because no source")
    lines.append("documentation supports a deterministic derivation. They are")
    lines.append("flagged in `flagged_for_review.csv` for human input.")
    lines.append("")
    lines.append("### bor_bin (all 9 template trials)")
    lines.append("- Template does NOT track clinical_benefit.binary alone (SD splits 99/178 between bor_bin=0/1).")
    lines.append("- Hypothesis: `1 iff (clinical_benefit.binary='R') OR (clinical_benefit.binary='SD' AND pfs_time>=183)` — match 86% / 78% on s1400i / EAY131_Z1D.")
    lines.append("- **NOT committed** per the no-silent-guessing policy.")
    lines.append("")
    lines.append("### pfs_bin (all 9 template trials)")
    lines.append("- Template does NOT track pfs_stat directly.")
    lines.append("- Hypothesis: `1 iff (pfs_time>=183) OR (pfs_stat=0)` — match 81% / 81% on s1400i / EAY131_Z1D.")
    lines.append("- **NOT committed** per policy.")
    lines.append("")
    lines.append("### S1400I `age`")
    lines.append("- Template age values are decimals (per-sample). Source `age_num` is integer enrollment age.")
    lines.append("- Per-sample collection date NOT present in any S1400I source file.")
    lines.append("- **Will stay NA** unless an external sample-collection-date file is supplied.")
    lines.append("")
    lines.append("### `Cimac.id` for 10013 and 14C0059G (new trials)")
    lines.append("- Exhaustive scan of every cell of every file in both trial dirs for any string starting with a known `cimac_part_id` and followed by a sample-suffix: **zero hits**.")
    lines.append("- External CIMAC sample manifest required.")
    lines.append("")

    # ── Section 4: assumptions COMMITTED into YAML ────────────────────
    lines.append("## 4. Assumptions committed into `scripts/config/harmonization_config.yaml`")
    lines.append("")
    lines.append("Every committed mapping has supporting evidence (cross-tab, codebook, or empirical column scan). Specific examples:")
    lines.append("")
    lines.append("| Trial | Field | Committed rule | Evidence |")
    lines.append("|---|---|---|---|")
    lines.append("| S1400I | phase | A iff `cimac_part_id` starts with `CCZR`, B iff `CNKA` | Cross-tab: 54/54 A patients = CCZR prefix, 106/106 B = CNKA |")
    lines.append("| S1400I | os_time, pfs_time | months × 30.4375 → days | Empirical conversion factor matches template exactly |")
    lines.append("| EAY131_Z1D | arm | = raw A3 (Gender) value | Template-bug reproduction (40 Female + 23 Male = 63 rows) |")
    lines.append("| 10104 | os_time, pfs_time | anchor = `first_cycle_first_day` | Match 83% vs 9% for PT_REG_DT_INT anchor (P1#1) |")
    lines.append("| 10104 | treatment | arm_code map: ARM A1/A2→cabo_nivo; ARM B→ARM B; C-Carcino/C-Prior IO→cabo_nivo; crossover→ARM B | Cross-tab template treatment × arm_code (P1#2) |")
    lines.append("| 10104 | race | fallback `PT_RACE_CD_1` → `PT_RACE_CD_2` | 12 black patients only present in CD_2 (P2#2) |")
    lines.append("| 10026 | Collection_Event_alt | End_of_Cycle_7→C8, End_of_Cycle_10→C12, Other→EOT | Direct template cross-tab (P2#1) |")
    lines.append("| 10021 | clinical_benefit | RECIST clinical benefit status: `Clinical Benefit→Clin-Ben`, `No Clinical Benefit→No C-B` | Template clinical_benefit values literal |")
    lines.append("| 10021 | clinical_benefit.binary | `Clin-Ben → R`, `No C-B → NR` | Template cross-tab clinical_benefit × clinical_benefit.binary (P1#4) |")
    lines.append("| 10021 | race | `Afr-American → black`, `Not reported → unk` | Source uses literal `Afr-American` and lowercase `r` (P2#3) |")
    lines.append("| 9204 | treatment | by file membership: ipi or nivo demographics file | Trial design (paired arm files) |")
    lines.append("| 9204 | clinical_benefit.binary | `Morphological Complete Remission→R`, `Partial Remission→R`, `Persistent Disease→NR`, `Progression→NR`, `Not Applicable→other` | Template cross-tab (P3 pass) |")
    lines.append("| GU16-257 | clinical_benefit | source column = `CLCRFL` (Y/N/NE) | Exhaustive column scan: 74/74 perfect match (P1#7) |")
    lines.append("| GU16-257 | phase | source column = `METRC` (Y/N) | Exhaustive column scan: 74/74 perfect match (P1#9) |")
    lines.append("| GU16-257 | race | numeric codes: 1→white, 3→black, 5→asian, 99→unk | Template cross-tab (P2#4); NOT the CIDC standard |")
    lines.append("| ABTC1603 | clinical_benefit / clinical_benefit.binary | **Gold outputs:** derived from a 4-month / 120-day PFS cutoff (Dr. Ye, 2026-06-17): `pfs_time≥120 → Clin-Ben / R`, `pfs_time<120 → No C-B / NR`, regardless of death reason. ABTC1603 has no BOR/response source column. | Gold deliverables only (harmonized_9trials_gold.csv, harmonized_11trials.csv). pfs_time, pfs_stat, pfs_bin, bor_bin unchanged. The historical harmonized_9trials_reproduced.csv stays template-aligned (clinical_benefit NaN, clinical_benefit.binary constant `other`, all 148 rows; P1#3). |")
    lines.append("| ABTC1603 | os_stat | `DEAD→1, ALIVE→0` (uppercase, source uses caps) | Source `Vital Status` values |")
    lines.append("| ABTC1603 | os_time | composite: Days to Death if dead, else Days to Last Contact | 39/42 match (3 are NaN, P2#5) |")
    lines.append("| ABTC1603 | pfs_time | composite: Days to Progression if non-null, else Days to Death if dead, else Days to Last Contact | 39/42 match (P2#5) |")
    lines.append("| E4412 | treatment | letter codes A/B/C → BV+ipi, D/E/F → BV+nivo, G/H/I → BV+nivo+ipi | `baseline_outcomes.xlsx` Codebook sheet (P1#6) |")
    lines.append("| E4412 | os_time, pfs_time | source `_wk` columns are actually months → × 30.4375 → days | Empirical: 0.41889 × 30.4 ≈ 13 (template value); name is misleading (P1#5) |")
    lines.append("")

    # ── Section 5: hypotheses NOT committed ───────────────────────────
    lines.append("## 5. Hypotheses tested but NOT committed (require human confirmation)")
    lines.append("")
    lines.append("| Field | Candidate rule | Match rate | Why not committed |")
    lines.append("|---|---|---|---|")
    lines.append("| bor_bin | `1 iff R OR (SD AND pfs_time>=183 days)` | 86% (s1400i), 78% (Z1D) | Not 100%; threshold (183d) is a guess based on the standard '6-month clinical benefit' convention but trial-specific landmarks are unknown |")
    lines.append("| pfs_bin | `1 iff pfs_time>=183 OR pfs_stat=0` | 81% (s1400i), 81% (Z1D) | Not 100%; rule is a hypothesis only |")
    lines.append("| S1400I age | derive sample age = enrollment age + (collection_date - enrollment_date) / 365.25 | (cannot test) | No per-sample collection date in any S1400I source file |")
    lines.append("")

    # ── Section 6: trials/fields requiring human review ───────────────
    lines.append("## 6. Trials / fields requiring human review")
    lines.append("")
    lines.append("Below-1.0 (trial, column) cells in the 9-trial template that are NOT policy-driven NA. Review `validation_report.csv` for specifics:")
    lines.append("")
    res = val_sum[val_sum["match_rate"] < 1.0].sort_values("match_rate")
    res = res[~res["column"].isin({"bor_bin", "pfs_bin"})]
    # Exclude S1400I age (policy)
    res = res[~((res["trial"]=="CIMAC-s1400i") & (res["column"]=="age"))]
    if res.empty:
        lines.append("- (none; all non-policy cells at 1.000)")
    else:
        for _, r in res.iterrows():
            n = int(r["n_rows"])
            mr = float(r["match_rate"])
            n_match = int(round(mr * n))
            lines.append(f"- **{r['trial']}** `{r['column']}`: match {mr:.3f} ({n_match}/{n} rows)")
    lines.append("")

    # New trial fields needing review
    lines.append("New trials (no template ground truth — review against source documentation):")
    new = handoff_csv[(~handoff_csv["is_template_trial"]) & (handoff_csv["status"].isin({"ALL_NA", "MOSTLY_FLAGGED"}))]
    if new.empty:
        lines.append("- (all new-trial fields populated from source)")
    else:
        for _, r in new.iterrows():
            lines.append(f"- **{r['trial']}** `{r['field']}`: {r['status']} (n_rows={r['n_rows']}, n_flagged={r['n_flagged']})")
    lines.append("")

    # ── Section 7: re-run commands ────────────────────────────────────
    lines.append("## 7. How to re-run the pipeline")
    lines.append("")
    lines.append("After editing `scripts/config/harmonization_config.yaml` or any extractor:")
    lines.append("")
    lines.append("```bash")
    lines.append("cd /gpfs/gsfs12/users/nextgen2/james/data/CIMAC/harmonization")
    lines.append("")
    lines.append("# Refresh file inventory (optional, only needed if source files changed)")
    lines.append(".venv/bin/python scripts/inspect_trial_files.py")
    lines.append("")
    lines.append("# Run the harmonization pipeline (always)")
    lines.append(".venv/bin/python scripts/extract_harmonized_clinical.py")
    lines.append("")
    lines.append("# Validate against the 9-trial template")
    lines.append(".venv/bin/python scripts/validate_extractions.py")
    lines.append("")
    lines.append("# Refresh the review / handoff reports")
    lines.append(".venv/bin/python scripts/generate_review_report.py")
    lines.append(".venv/bin/python scripts/build_review_checklist.py")
    lines.append(".venv/bin/python scripts/build_final_handoff.py")
    lines.append("```")
    lines.append("")
    lines.append("To run only a subset of trials:")
    lines.append("")
    lines.append("```bash")
    lines.append(".venv/bin/python scripts/extract_harmonized_clinical.py \\")
    lines.append("    --trials 'S1400I-clinical,EAY131-Z1D-clinical'")
    lines.append("```")
    lines.append("")

    # ── Section 8: recommended next steps ─────────────────────────────
    lines.append("## 8. Recommended next manual review steps")
    lines.append("")
    lines.append("Ordered by impact:")
    lines.append("")
    lines.append("1. **Confirm `bor_bin` / `pfs_bin` derivation rule** by looking at the original analysis SAP or asking the trial statistician. The tested hypotheses are in section 5 above; provide threshold + criteria and one YAML edit + re-run will populate ~1700 rows.")
    lines.append("2. **Supply CIMAC sample manifest for 10013 and 14C0059G** to populate `Cimac.id` (currently 219 NA + flagged rows).")
    lines.append("3. **Supply S1400I per-sample collection dates** (CSV with `cimac_part_id`, `Cimac.id`, `collection_date`) to enable decimal age computation.")
    lines.append("4. **Review remaining sub-1.000 cells** in section 6 — most are 90%+ matches with small NaN-vs-NaN or borderline cases; spot-check `validation_report.csv` filtered by (trial, column).")
    lines.append("5. **Confirm 10013 / 14C0059G `Collection_Event_alt` bucketing** (Baseline / C2 / etc.) once sample manifests are available.")
    lines.append("")

    # ── Section 9: change log ──────────────────────────────────────────
    lines.append("## 9. Change log across the three review passes")
    lines.append("")
    lines.append("| Pass | Items resolved | Mismatch count |")
    lines.append("|---|---|---:|")
    lines.append("| Initial 9-trial pipeline | architecture, 9 of 9 trials | 5,406 |")
    lines.append("| P1 | 10104 os/pfs anchor, 10104 treatment, ABTC1603 clinical_benefit.binary, 10021 clinical_benefit.binary, E4412 os/pfs unit, E4412 treatment, GU16-257 clinical_benefit/phase/clinical_benefit.binary | 3,759 |")
    lines.append("| P2 | 10026 Collection_Event_alt, race fixes (10104/10021/GU16-257), ABTC1603 os/pfs composite, Cimac.id scan documented | 3,566 |")
    lines.append("| P3 | 9204 clinical_benefit.binary long-form codes | 3,545 |")
    lines.append("| Exclusion + ordering pass | BACCI removed from registry/config; harmonized_9trials_reproduced.csv reordered to match template; renamed harmonized_12trials.csv → harmonized_11trials.csv | — |")
    lines.append("")
    lines.append(f"Final state: **{len(harmonized)} harmonized rows**, "
                 f"**{len(prov)} provenance cells**, **{len(flagged)} flagged cells**, "
                 f"**{int(tpl_only['status'].value_counts().get('OK', 0))} of 135 template (trial, column) cells at ≥0.95 match**.")
    lines.append("")

    md_path.write_text("\n".join(lines))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(OUTDIR))
    args = ap.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    outdir = Path(args.out)

    harmonized = pd.read_csv(outdir / "harmonized_11trials.csv")
    val_sum    = pd.read_csv(outdir / "validation_summary.csv")
    flagged    = pd.read_csv(outdir / "flagged_for_review.csv")
    prov       = pd.read_csv(outdir / "provenance_long.csv")

    df = build_csv_table(harmonized, val_sum, flagged)
    csv_path = outdir / "final_handoff_report.csv"
    df.to_csv(csv_path, index=False)
    LOG.info("Wrote %s (%d rows)", csv_path, len(df))

    row_order_path = outdir / "row_order_diagnostics.csv"
    row_order = pd.read_csv(row_order_path) if row_order_path.exists() else None

    md_path = outdir / "final_handoff_report.md"
    write_md(df, val_sum, harmonized, flagged, prov, md_path, row_order=row_order)
    LOG.info("Wrote %s", md_path)

    print("\nStatus counts (template trials × 15 columns):")
    tpl_df = df[df["is_template_trial"]]
    print(tpl_df["status"].value_counts().to_string())
    print("\nStatus counts (new trials):")
    new_df = df[~df["is_template_trial"]]
    print(new_df["status"].value_counts().to_string())


if __name__ == "__main__":
    main()
