"""
build_gu16257_pfs_time_investigation.py — Regenerate the GU16-257 pfs_time
fallback-column investigation report.

Read-only. Joins the 9-trial template (subset trial='CIMAC-gu16257') against
GU16-257-clinical/response.2023-01-04.csv on cimac_part_id and tests each
candidate column as a fallback for template `pfs_time`.

Writes:
  harmonization_outputs/gu16257_pfs_time_fallback_investigation.md
"""
from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "scripts"))

from lib.cidc_io import read_cidc_csv  # noqa: E402

LOG = logging.getLogger("gu16257-pfs-time-investigation")

CANDIDATES = ["DFSTIM", "OSTIM", "LRFSTIM", "BIDFSTIM", "DRFSTIM"]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--template",
                    default=str(PROJECT_ROOT / "cross_trial_analysis_egk_april30_meta_9trials.csv"))
    ap.add_argument("--response",
                    default=str(PROJECT_ROOT / "GU16-257-clinical" / "response.2023-01-04.csv"))
    ap.add_argument("--out",
                    default=str(PROJECT_ROOT / "harmonization_outputs"
                                / "gu16257_pfs_time_fallback_investigation.md"))
    args = ap.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")

    tpl = pd.read_csv(args.template, index_col=0)
    g = tpl[tpl["trial"] == "CIMAC-gu16257"][["cimac_part_id", "pfs_time"]].copy()
    resp = read_cidc_csv(args.response).df

    # Per-source NaN counts for context
    src_nan = {c: int(resp[c].isna().sum()) for c in CANDIDATES if c in resp.columns}
    src_pop = {c: int(resp[c].notna().sum()) for c in CANDIDATES if c in resp.columns}

    m = g.merge(resp[["cimac_part_id"] + CANDIDATES], on="cimac_part_id", how="left")
    n_total = len(m)
    n_tpl_present = int(m["pfs_time"].notna().sum())

    # Affected rows: template has value AND DFSTIM is NaN
    affected = m[m["pfs_time"].notna() & m["DFSTIM"].isna()]
    n_affected = len(affected)
    n_affected_uniq = affected["cimac_part_id"].nunique()

    # Per-candidate match within affected
    aff_match = {}
    for c in CANDIDATES:
        if c in affected:
            aff_match[c] = int((affected["pfs_time"] == affected[c]).sum())

    # Full-trial rules
    def equal_with_na(a, b):
        return (a == b) | (a.isna() & b.isna())

    rule_results = {}
    rule_results["DFSTIM only (current YAML)"] = int(equal_with_na(m["pfs_time"], m["DFSTIM"]).sum())
    rule_results["DRFSTIM only"]               = int(equal_with_na(m["pfs_time"], m["DRFSTIM"]).sum())
    m["c_dos"]  = m["DFSTIM"].where(m["DFSTIM"].notna(), m["OSTIM"])
    rule_results["DFSTIM if not NaN else OSTIM"]   = int(equal_with_na(m["pfs_time"], m["c_dos"]).sum())
    m["c_drfs"] = m["DFSTIM"].where(m["DFSTIM"].notna(), m["DRFSTIM"])
    rule_results["DFSTIM if not NaN else DRFSTIM"] = int(equal_with_na(m["pfs_time"], m["c_drfs"]).sum())

    # Remaining unexplained under chosen rule
    chosen_rule_col = "c_drfs"
    unexp = m[~equal_with_na(m["pfs_time"], m[chosen_rule_col])]
    unexp_pat = unexp.drop_duplicates("cimac_part_id")

    # ─── Build markdown ─────────────────────────────────────────────────
    lines: list[str] = []
    lines.append("# CIMAC-gu16257 `pfs_time` fallback investigation")
    lines.append("")
    lines.append("Generated by `scripts/build_gu16257_pfs_time_investigation.py`. ")
    lines.append("Read-only; no code or harmonized outputs changed in producing this report.")
    lines.append("")
    lines.append(f"Source: `{Path(args.response).name}` joined per-row to template ")
    lines.append(f"`{Path(args.template).name}` (subset `trial == 'CIMAC-gu16257'`). ")
    lines.append(f"{n_total} template rows, {g['cimac_part_id'].nunique()} unique patients.")
    lines.append("")

    lines.append("## Candidate columns")
    lines.append("")
    lines.append("| column | rows with non-NaN value in source |")
    lines.append("|---|---:|")
    for c in CANDIDATES:
        lines.append(f"| `{c}` | {src_pop.get(c, 0)} |")
    lines.append("")

    lines.append(f"## Affected rows: template has `pfs_time`, source `DFSTIM` is NaN")
    lines.append("")
    lines.append(f"- n_rows: **{n_affected}**  (unique patients: {n_affected_uniq})")
    lines.append("")
    lines.append("| candidate | matches affected | rate |")
    lines.append("|---|---:|---:|")
    for c in CANDIDATES:
        n = aff_match.get(c, 0)
        rate = (n / n_affected) if n_affected else 0
        lines.append(f"| `{c}` | {n} | {rate:.1%} |")
    lines.append("")

    lines.append(f"## Full-trial rules (n={n_total})")
    lines.append("")
    lines.append("| rule | match | rate |")
    lines.append("|---|---:|---:|")
    for name, n in rule_results.items():
        rate = n / n_total
        lines.append(f"| `{name}` | {n} | {rate:.3f} |")
    lines.append("")

    lines.append(f"## Remaining unexplained rows under `DFSTIM if not NaN else DRFSTIM` ({len(unexp)} rows, {unexp_pat['cimac_part_id'].nunique()} patient(s))")
    lines.append("")
    if unexp.empty:
        lines.append("(none)")
    else:
        lines.append("| cimac_part_id | template pfs_time | DFSTIM | OSTIM | LRFSTIM | BIDFSTIM | DRFSTIM |")
        lines.append("|---|---:|---:|---:|---:|---:|---:|")
        for _, r in unexp_pat.iterrows():
            lines.append(
                f"| {r['cimac_part_id']} | {r['pfs_time']} | {r['DFSTIM']} | "
                f"{r['OSTIM']} | {r['LRFSTIM']} | {r['BIDFSTIM']} | {r['DRFSTIM']} |"
            )
    lines.append("")

    lines.append("## Recommendation")
    lines.append("")
    lines.append("Use the rule `pfs_time = DFSTIM if not NaN else DRFSTIM`. ")
    lines.append(f"It matches {rule_results['DFSTIM if not NaN else DRFSTIM']}/{n_total} ")
    lines.append(f"({rule_results['DFSTIM if not NaN else DRFSTIM']/n_total:.3f}) of template rows. ")
    lines.append("Remaining unexplained rows should stay flagged for human review rather than ")
    lines.append("being hard-coded around.")
    lines.append("")

    Path(args.out).write_text("\n".join(lines))
    LOG.info("Wrote %s", args.out)


if __name__ == "__main__":
    main()
